/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stokper;

import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;/**
 *
 * @author sniff
 */
public class urSatia extends javax.swing.JFrame {

    /**
     * Creates new form urSatia
     */
    public urSatia() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
            cr.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);


            for (int i = 0; i < ktablo.getColumnCount(); i++) {
            ktablo.getColumnModel().getColumn(i).setCellRenderer(cr);
            }
            odLBL.setText("0.0");
            topLBL.setText("0.0");
            puLBL.setText("0.0");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTXT1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktablo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        topLBL = new javax.swing.JLabel();
        odLBL = new javax.swing.JLabel();
        puLBL = new javax.swing.JLabel();
        creditBTN = new javax.swing.JButton();
        cashBTN = new javax.swing.JButton();
        cancelBTN = new javax.swing.JButton();
        finishBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mikTXT = new javax.swing.JTextField();
        baTXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        onBTN = new javax.swing.JButton();
        elBTN = new javax.swing.JButton();
        besBTN = new javax.swing.JButton();
        yuzBTN = new javax.swing.JButton();
        ikBTN = new javax.swing.JButton();
        yirBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        delBTN = new javax.swing.JButton();
        refBTN = new javax.swing.JButton();
        odBTN = new javax.swing.JButton();
        cashTXT = new javax.swing.JTextField();

        addTXT1.setText("Ekle");
        addTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTXT1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("StokPer");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setText("Satış İşlemleri");

        backbtn.setText("Geri");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        ktablo.setBackground(new java.awt.Color(204, 255, 255));
        ktablo.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        ktablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Barkod", "Ürün Adı", "Ürün Grubu", "Miktar", "Birim", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ktablo.setToolTipText("");
        ktablo.setGridColor(new java.awt.Color(204, 255, 255));
        ktablo.setInheritsPopupMenu(true);
        ktablo.setRowHeight(35);
        ktablo.setRowMargin(1);
        ktablo.setRowSelectionAllowed(false);
        ktablo.setSelectionBackground(new java.awt.Color(51, 102, 255));
        ktablo.setShowGrid(true);
        ktablo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ktablo);
        if (ktablo.getColumnModel().getColumnCount() > 0) {
            ktablo.getColumnModel().getColumn(0).setResizable(false);
            ktablo.getColumnModel().getColumn(1).setResizable(false);
            ktablo.getColumnModel().getColumn(2).setResizable(false);
            ktablo.getColumnModel().getColumn(3).setResizable(false);
            ktablo.getColumnModel().getColumn(4).setResizable(false);
            ktablo.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        topLBL.setBackground(new java.awt.Color(204, 204, 204));
        topLBL.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        topLBL.setForeground(new java.awt.Color(0, 0, 204));
        topLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLBL.setToolTipText("");
        topLBL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOPLAM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12))); // NOI18N
        topLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        odLBL.setBackground(new java.awt.Color(204, 204, 204));
        odLBL.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        odLBL.setForeground(new java.awt.Color(153, 0, 153));
        odLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odLBL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ÖDENEN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12))); // NOI18N

        puLBL.setBackground(new java.awt.Color(204, 204, 204));
        puLBL.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        puLBL.setForeground(new java.awt.Color(255, 0, 0));
        puLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puLBL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PARA ÜSTÜ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 12))); // NOI18N

        creditBTN.setBackground(new java.awt.Color(102, 153, 255));
        creditBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        creditBTN.setText("Kredi Kartı");
        creditBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        creditBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        creditBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditBTNActionPerformed(evt);
            }
        });

        cashBTN.setBackground(new java.awt.Color(255, 102, 0));
        cashBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        cashBTN.setText("Nakit");
        cashBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cashBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashBTNActionPerformed(evt);
            }
        });

        cancelBTN.setBackground(new java.awt.Color(204, 0, 0));
        cancelBTN.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        cancelBTN.setText("İptal");
        cancelBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        finishBTN.setBackground(new java.awt.Color(51, 255, 51));
        finishBTN.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        finishBTN.setText("Fiş Çıkart");
        finishBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        finishBTN.setEnabled(false);
        finishBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cashBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creditBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(odLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(topLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(creditBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(topLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cashBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finishBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(cancelBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setText("Barkod");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Miktar");

        mikTXT.setPreferredSize(null);
        mikTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mikTXTActionPerformed(evt);
            }
        });

        baTXT.setPreferredSize(null);
        baTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baTXTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("X");

        addBTN.setBackground(new java.awt.Color(153, 255, 255));
        addBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        addBTN.setText("Ekle");
        addBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        onBTN.setBackground(new java.awt.Color(204, 204, 204));
        onBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        onBTN.setText("₺10");
        onBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBTNActionPerformed(evt);
            }
        });

        elBTN.setBackground(new java.awt.Color(204, 204, 204));
        elBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        elBTN.setText("₺50");
        elBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        elBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elBTNActionPerformed(evt);
            }
        });

        besBTN.setBackground(new java.awt.Color(204, 204, 204));
        besBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        besBTN.setText("₺5");
        besBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        besBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besBTNActionPerformed(evt);
            }
        });

        yuzBTN.setBackground(new java.awt.Color(204, 204, 204));
        yuzBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        yuzBTN.setText("₺100");
        yuzBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yuzBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yuzBTNActionPerformed(evt);
            }
        });

        ikBTN.setBackground(new java.awt.Color(204, 204, 204));
        ikBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ikBTN.setText("₺200");
        ikBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ikBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikBTNActionPerformed(evt);
            }
        });

        yirBTN.setBackground(new java.awt.Color(204, 204, 204));
        yirBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        yirBTN.setText("₺20");
        yirBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yirBTNActionPerformed(evt);
            }
        });

        delBTN.setBackground(new java.awt.Color(204, 204, 255));
        delBTN.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        delBTN.setText("Sil");
        delBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTNActionPerformed(evt);
            }
        });

        refBTN.setBackground(new java.awt.Color(255, 204, 204));
        refBTN.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        refBTN.setText("İade");
        refBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        odBTN.setBackground(new java.awt.Color(204, 204, 204));
        odBTN.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        odBTN.setText("Ödenen");
        odBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        odBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odBTNActionPerformed(evt);
            }
        });

        cashTXT.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        cashTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cashTXT.setText("0");
        cashTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cashTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(elBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yuzBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ikBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(besBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yirBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(odBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(baTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(mikTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mikTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(besBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(onBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yirBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ikBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yuzBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(odBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cashTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void mikTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mikTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mikTXTActionPerformed

    private void baTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baTXTActionPerformed

    private void creditBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditBTNActionPerformed
     besBTN.setEnabled(false);
    cashBTN.setEnabled(false);
    creditBTN.setEnabled(false);
    yirBTN.setEnabled(false);
    yuzBTN.setEnabled(false);
    elBTN.setEnabled(false);
    ikBTN.setEnabled(false);
    delBTN.setEnabled(false);
    odBTN.setEnabled(false);
    onBTN.setEnabled(false);
    refBTN.setEnabled(false);
    addBTN.setEnabled(false);
    finishBTN.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_creditBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
       
       String mikTar = mikTXT.getText().trim();
       String barkod = baTXT.getText().trim();
        DefaultTableModel model = (DefaultTableModel) ktablo.getModel();
      
        if ((barkod.isEmpty())){
          JOptionPane.showMessageDialog(this, "Lütfen boş alanları doldurunuz.");
          return;
          
      }
       try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
           
           PreparedStatement ps = conn.prepareStatement("SELECT * FROM urunler WHERE id = ?");
           ps.setString(1, barkod);
           ResultSet rs = ps.executeQuery();
            
           while (rs.next()){
               double fiyat = rs.getDouble("Fiyat");
               double fiyTop = Double.parseDouble(mikTar) * fiyat;
               Object[] row = {
                        rs.getInt("id"),        
                        rs.getString("ad"),
                        rs.getString("ugrup"),     
                        mikTar,  
                        rs.getString("birim"),
                        fiyTop}; 
               model.insertRow(0, row); 
               }
           
           rs.close();
           ps.close();
           conn.close();
           
       }catch (Exception ex) {
            Logger.getLogger(urSatia.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Veri çekme hatası: " + ex.getMessage());
        }
       
       double fiyTop = 0;
       int fiySut = 5;

        for (int i = 0; i < ktablo.getRowCount(); i++) {
            Object exp = ktablo.getValueAt(i, fiySut);

            if (exp != null && !exp.toString().isEmpty()) {
                try {
                    fiyTop += Double.parseDouble(exp.toString());
                } catch (NumberFormatException e) {
                    System.out.println("Geçersiz sayı: " + exp);
                }
        }
        }
       
      topLBL.setText(String.valueOf(fiyTop));
    
           // TODO add your handling code here:
    }//GEN-LAST:event_addBTNActionPerformed

    private void cashBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashBTNActionPerformed
    besBTN.setEnabled(false);
    cashBTN.setEnabled(false);
    creditBTN.setEnabled(false);
    yirBTN.setEnabled(false);
    yuzBTN.setEnabled(false);
    elBTN.setEnabled(false);
    ikBTN.setEnabled(false);
    delBTN.setEnabled(false);
    odBTN.setEnabled(false);
    onBTN.setEnabled(false);
    refBTN.setEnabled(false);
    addBTN.setEnabled(false);
    finishBTN.setEnabled(true);
    }//GEN-LAST:event_cashBTNActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
    besBTN.setEnabled(true);
    cashBTN.setEnabled(true);
    creditBTN.setEnabled(true);
    yirBTN.setEnabled(true);
    yuzBTN.setEnabled(true);
    elBTN.setEnabled(true);
    ikBTN.setEnabled(true);
    delBTN.setEnabled(true);
    odBTN.setEnabled(true);
    onBTN.setEnabled(true);
    refBTN.setEnabled(true);
    addBTN.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void addTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTXT1ActionPerformed

    private void onBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBTNActionPerformed
      double on = 10;
    on += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(on));// 
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));// TODO add your handling code here:
    }//GEN-LAST:event_onBTNActionPerformed

    private void elBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elBTNActionPerformed
      double elli = 50;
    elli += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(elli));//
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));// TODO add your handling code here:
    }//GEN-LAST:event_elBTNActionPerformed

    private void besBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besBTNActionPerformed
    double bes = 5;
    bes += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(bes));//
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));// TODO add your handling code here:
    }//GEN-LAST:event_besBTNActionPerformed

    private void yuzBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yuzBTNActionPerformed
    double yuz = 100;
    yuz += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(yuz));
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));// TODO add your handling code here:
    }//GEN-LAST:event_yuzBTNActionPerformed

    private void ikBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikBTNActionPerformed
     double ikYuz = 200;
    ikYuz += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(ikYuz));
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));
    }//GEN-LAST:event_ikBTNActionPerformed

    private void yirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yirBTNActionPerformed
      double yir = 20;
    yir += Double.valueOf(odLBL.getText());
    odLBL.setText(String.valueOf(yir));
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));
    //  // TODO add your handling code here:
    }//GEN-LAST:event_yirBTNActionPerformed

    private void cashTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashTXTActionPerformed

    private void delBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTNActionPerformed
     DefaultTableModel model = (DefaultTableModel) ktablo.getModel();
        int serow = ktablo.getSelectedRow();

    if (serow != -1) {
        model.removeRow(serow);
    } else {
        JOptionPane.showMessageDialog(this, "Lütfen silinecek bir satır seçin.");
}       
       double fiyTop = 0;
       int fiySut = 5;

        for (int i = 0; i < ktablo.getRowCount(); i++) {
            Object exp = ktablo.getValueAt(i, fiySut);

            if (exp != null && !exp.toString().isEmpty()) {
                try {
                    fiyTop += Double.parseDouble(exp.toString());
                } catch (NumberFormatException e) {
                    System.out.println("Geçersiz sayı: " + exp);
                }
        }
        }
       
      topLBL.setText(String.valueOf(fiyTop));
        double top = 0;
        top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
        puLBL.setText(String.valueOf(top));// TODO add your handling code here:
    }//GEN-LAST:event_delBTNActionPerformed

    private void refBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refBTNActionPerformed
    int selectedRow = ktablo.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) ktablo.getModel();

        if (selectedRow != 1) {
            String selectedID = ktablo.getValueAt(selectedRow, 0).toString();
            int onay = JOptionPane.showConfirmDialog(this, "Ürünü iade etmeyi onaylıyor musun?");
            
        if (onay == JOptionPane.YES_OPTION){
            try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
        
                for( int i = 0; i<model.getRowCount(); i++){
            
                    Object barkodob = model.getValueAt(i, 0);
                    Object adetob = model.getValueAt(i, 3);
            
                    if (barkodob !=null && adetob !=null) {
                        String barkod = barkodob.toString();
                         int satisadet = Integer.parseInt(adetob.toString());
                
                        String sql = "UPDATE urunler SET stok = stok + ? WHERE id = ?;";
                        PreparedStatement pst = conn.prepareStatement(sql);   
                
                        pst.setInt(1, satisadet);
                        pst.setString(2, barkod);
                        pst.executeUpdate();
            }}}
            catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
            }}
        
        if (onay == JOptionPane.YES_OPTION){
            
            
            try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
                String sql = "INSERT INTO satislar (urun_id, adet, ad, birim, ugrup, fiyat, islem) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
        
        for( int i = 0; i<model.getRowCount(); i++){
            
            Object barkod = model.getValueAt(i, 0);
            Object adet = model.getValueAt(i, 3);
            Object ad = model.getValueAt(i, 1);
            Object bir = model.getValueAt(i, 4);
            Object grp = model.getValueAt(i, 2);
            Object fiy = model.getValueAt(i, 5);
            
            if (barkod !=null && adet !=null && ad !=null && bir !=null && grp !=null && fiy !=null) { 
            String islem = "İade";
            
            
            ps.setString(1, barkod.toString());
            ps.setString(2, adet.toString());
            ps.setString(3, ad.toString());
            ps.setString(4, bir.toString());
            ps.setString(5, grp.toString());
            ps.setDouble(6, Double.parseDouble(fiy.toString()));
            ps.setString(7, islem);
            
            ps.executeUpdate();
            }
        }
        JOptionPane.showMessageDialog(null, "İade tamamlandı..");
        
    }    
     catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    }}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_refBTNActionPerformed

    private void odBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odBTNActionPerformed
    double cash = Double.parseDouble(cashTXT.getText());
    odLBL.setText(String.valueOf(cash));
    double top = 0;
    top = Double.valueOf(odLBL.getText()) - Double.valueOf(topLBL.getText());
    puLBL.setText(String.valueOf(top));
    // TODO add your handling code here:
    }//GEN-LAST:event_odBTNActionPerformed

    private void finishBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBTNActionPerformed
    DefaultTableModel model = (DefaultTableModel) ktablo.getModel();
    
   
    try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
        String sql = "INSERT INTO satislar (urun_id, adet, ad, birim, ugrup, fiyat, islem) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        
        for( int i = 0; i<model.getRowCount(); i++){
            
            Object barkod = model.getValueAt(i, 0);
            Object adet = model.getValueAt(i, 3);
            Object ad = model.getValueAt(i, 1);
            Object bir = model.getValueAt(i, 4);
            Object grp = model.getValueAt(i, 2);
            Object fiy = model.getValueAt(i, 5);
            
            if (barkod !=null && adet !=null && ad !=null && bir !=null && grp !=null && fiy !=null) { 
            String islem = "Satış";
            
            
            ps.setString(1, barkod.toString());
            ps.setString(2, adet.toString());
            ps.setString(3, ad.toString());
            ps.setString(4, bir.toString());
            ps.setString(5, grp.toString());
            ps.setDouble(6, Double.parseDouble(fiy.toString()));
            ps.setString(7, islem);
            
            ps.executeUpdate();
            }
        }
        JOptionPane.showMessageDialog(null, "Satış tamamlandı.");
        
    }    
     catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    }
    
    try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
        
        
        
        for( int i = 0; i<model.getRowCount(); i++){
            
            Object barkodob = model.getValueAt(i, 0);
            Object adetob = model.getValueAt(i, 3);
            
            if (barkodob !=null && adetob !=null) {
                String barkod = barkodob.toString();
                int satisadet = Integer.parseInt(adetob.toString());
                
                String sql = "UPDATE urunler SET stok = stok - ? WHERE id = ?;";
                PreparedStatement pst = conn.prepareStatement(sql);   
                
                pst.setInt(1, satisadet);
                pst.setString(2, barkod);
                
            
            
                pst.executeUpdate();
            }
        }
        
        
    }    
     catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    }
    model.setRowCount(0);
    odLBL.setText("0.0");
    topLBL.setText("0.0");
    puLBL.setText("0.0");
    besBTN.setEnabled(true);
    cashBTN.setEnabled(true);
    creditBTN.setEnabled(true);
    yirBTN.setEnabled(true);
    yuzBTN.setEnabled(true);
    elBTN.setEnabled(true);
    ikBTN.setEnabled(true);
    delBTN.setEnabled(true);
    odBTN.setEnabled(true);
    onBTN.setEnabled(true);
    refBTN.setEnabled(true);
    addBTN.setEnabled(true);
    }//GEN-LAST:event_finishBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urSatia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urSatia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urSatia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urSatia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urSatia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton addTXT1;
    private javax.swing.JTextField baTXT;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton besBTN;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton cashBTN;
    private javax.swing.JTextField cashTXT;
    private javax.swing.JButton creditBTN;
    private javax.swing.JButton delBTN;
    private javax.swing.JButton elBTN;
    private javax.swing.JButton finishBTN;
    private javax.swing.JButton ikBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ktablo;
    private javax.swing.JTextField mikTXT;
    private javax.swing.JButton odBTN;
    private javax.swing.JLabel odLBL;
    private javax.swing.JButton onBTN;
    private javax.swing.JLabel puLBL;
    private javax.swing.JButton refBTN;
    private javax.swing.JLabel topLBL;
    private javax.swing.JButton yirBTN;
    private javax.swing.JButton yuzBTN;
    // End of variables declaration//GEN-END:variables
}
