/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stokper;

import java.awt.Component;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author sniff
 */
public class users extends javax.swing.JFrame {
    
    /**
     * Creates new form users
     */
    public users() {
        try {
            initComponents();
            authoCombo.addItem("1");
            authoCombo.addItem("2");
            authoCombo.addItem("3");
            this.setLocationRelativeTo(null);
            KullaniciVerileriniGoster veriCekici = new KullaniciVerileriniGoster();
            veriCekici.verileriGetir(ktablo);
            
            
           
            
            
            DefaultTableCellRenderer cr = new DefaultTableCellRenderer();
            cr.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);


            for (int i = 0; i < ktablo.getColumnCount(); i++) {
            ktablo.getColumnModel().getColumn(i).setCellRenderer(cr);
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public class KullaniciVerileriniGoster {

    // Bu metod, mevcut JTable'ı alacak ve veritabanından veri çekip tabloya ekleyecek
    public void verileriGetir(JTable ktablo) throws Exception {
 

        // JTable modelini alıyoruz
        DefaultTableModel model = (DefaultTableModel) ktablo.getModel();

        try {
            Connection conn = VeritabaniBaglantisi.baglantiAc();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM kullanicilar");

           
            while (rs.next()) {
                Object[] row = {
                        rs.getInt("id"),        
                        rs.getString("adsoyad"),
                        rs.getString("kad"),     
                        rs.getString("telno"),   
                        rs.getString("yetki"),   
                        rs.getString("sifre")    
                };
                model.insertRow(0, row); 
            }

            // Bağlantıyı kapat
            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Veri çekme hatası: " + e.getMessage());
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NickTXT = new javax.swing.JTextField();
        uNameTXT = new javax.swing.JTextField();
        ConTXT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        passTXT = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        upBTN = new javax.swing.JButton();
        delBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktablo = new javax.swing.JTable();
        authoCombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(950, 653));

        backbtn.setText("Geri");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setText("KULLANICI İŞLEMLERİ");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setText("Ad Soyad");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Yetki");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("Telefon No");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setText("Kullanıcı Adı");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setText("Şifre");

        NickTXT.setPreferredSize(null);

        uNameTXT.setPreferredSize(null);
        uNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameTXTActionPerformed(evt);
            }
        });

        ConTXT.setPreferredSize(null);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        passTXT.setPreferredSize(null);
        passTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTXTActionPerformed(evt);
            }
        });

        jLabel8.setText("<html>1 ve 3 arası yetki veriniz.<br> - 1 Admin<br> - 2 Yönetici<br>  - 3 Personel</html>");

        addBTN.setBackground(new java.awt.Color(51, 255, 51));
        addBTN.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        addBTN.setText("Ekle");
        addBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        upBTN.setBackground(new java.awt.Color(0, 51, 255));
        upBTN.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        upBTN.setForeground(new java.awt.Color(204, 204, 204));
        upBTN.setText("Güncelle");
        upBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        upBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBTNActionPerformed(evt);
            }
        });

        delBTN.setBackground(new java.awt.Color(153, 0, 0));
        delBTN.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        delBTN.setText("Sil");
        delBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("StokPer");

        ktablo.setBackground(new java.awt.Color(51, 51, 51));
        ktablo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ktablo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ktablo.setForeground(new java.awt.Color(153, 153, 153));
        ktablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "AD SOYAD", "Kullanıcı Adı", "Telefon No", "Yetki", "Şifre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ktablo.setToolTipText("");
        ktablo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ktablo.setGridColor(new java.awt.Color(0, 0, 0));
        ktablo.setRowHeight(35);
        ktablo.setRowMargin(1);
        ktablo.setSelectionBackground(new java.awt.Color(102, 153, 255));
        ktablo.setShowGrid(true);
        ktablo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ktablo);
        if (ktablo.getColumnModel().getColumnCount() > 0) {
            ktablo.getColumnModel().getColumn(0).setResizable(false);
            ktablo.getColumnModel().getColumn(1).setResizable(false);
            ktablo.getColumnModel().getColumn(2).setResizable(false);
            ktablo.getColumnModel().getColumn(3).setResizable(false);
            ktablo.getColumnModel().getColumn(4).setResizable(false);
            ktablo.getColumnModel().getColumn(5).setResizable(false);
        }

        authoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authoComboActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 3));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("StokPer Kullanıcı İşlemleri yönetici tarafından işletmenin personel\nyönetimi için kullanılan bölümüdür. \n\nKullanıcı İşlemleri aşağıda belirtilmiş olan işlemleri yapacaktır;\n\n-Yetkilendirme: Kullanıcılar yetkilendirilerek, yetkiye göre program \nözelliklerine erişim sağlanması.\n-Kullanıcı Silme, Güncelleme, Ekleme\n\n");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(passTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(uNameTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ConTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(NickTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(authoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upBTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NickTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameTXTActionPerformed

    private void passTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTXTActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
    String uName = uNameTXT.getText().trim();
    String uNick = NickTXT.getText().trim();
    String contact = ConTXT.getText().trim();
    String autho = (String) authoCombo.getSelectedItem();
    String password = new String(passTXT.getPassword()).trim();
    
    if ((uName.isEmpty() || uNick.isEmpty() || contact.isEmpty() || password.isEmpty())) {
        JOptionPane.showMessageDialog(this, "Lütfen boş alanları doldurunuz.");
        return;
    }
    
    
        
    try (Connection conn = VeritabaniBaglantisi.baglantiAc()){
       String sql = "INSERT INTO kullanicilar (kad, sifre, yetki, adsoyad, telno) VALUES (?, ?, ?, ?, ?)";
       var as = conn.prepareStatement(sql);
       as.setString(1, uNick);
       as.setString(2, password);
       as.setString(3, autho);
       as.setString(4, uName);
       as.setString(5, contact);
       var sa = as.executeUpdate();
       
    if ((sa > 0)) {
        JOptionPane.showMessageDialog(this, "İşlem Başarılı");
            KullaniciVerileriniGoster veriCekici = new KullaniciVerileriniGoster();
            veriCekici.verileriGetir(ktablo);
    }else{
        JOptionPane.showMessageDialog(this, "Lütfen yetkiyi 1,2,3 şeklinde giriniz!");
    }
}
    catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata Oluştu");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_addBTNActionPerformed

    private void authoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authoComboActionPerformed

    private void delBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBTNActionPerformed
    int selectedRow = ktablo.getSelectedRow();
  
    if (selectedRow != -1) {
        String selectedID = ktablo.getValueAt(selectedRow, 0).toString();
        
        int onay = JOptionPane.showConfirmDialog(this, "Bu kullanıcıyı silmeyi onaylıyor musun?");
        if (onay == JOptionPane.YES_OPTION) {
            try {
                Connection conn = VeritabaniBaglantisi.baglantiAc();
                String sql = "DELETE FROM kullanicilar WHERE id = ?";
                var sa = conn.prepareStatement(sql);
                sa.setString(1, selectedID);
                int sonuc = sa.executeUpdate();
                
                if (sonuc > 0 ){
                    JOptionPane.showMessageDialog(this, "Kullanıcı başarıyla silindi!");
                    KullaniciVerileriniGoster veriCekici = new KullaniciVerileriniGoster();
                    veriCekici.verileriGetir(ktablo);
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Silme işlemi başarısız!");
                    
                }
                conn.close();
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hata: " +e.getMessage());
            }
        }
        
    }else{
        JOptionPane.showMessageDialog(this, "Lütfen silmek için bir kullanıcı seçin.");
    }
    }//GEN-LAST:event_delBTNActionPerformed

    private void upBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBTNActionPerformed
    int selectedRow = ktablo.getSelectedRow();
    String uName = uNameTXT.getText().trim();
    String uNick = NickTXT.getText().trim();
    String contact = ConTXT.getText().trim();
    String autho = (String) authoCombo.getSelectedItem();
    String password = new String(passTXT.getPassword()).trim();
    
    if ((uName.isEmpty() || uNick.isEmpty() || contact.isEmpty() || password.isEmpty())) {
        JOptionPane.showMessageDialog(this, "Lütfen boş alanları doldurunuz.");
        return;
    }
    
    if (selectedRow != 1) {
        String selectedID = ktablo.getValueAt(selectedRow, 0).toString();
        
        int onay = JOptionPane.showConfirmDialog(this, "Bu kullanıcıyı güncellemeyi onaylıyor musun?");
        
        if (onay == JOptionPane.YES_OPTION) {
            try {
                Connection conn = VeritabaniBaglantisi.baglantiAc();
                String sql = "UPDATE kullanicilar SET kad = ?, sifre = ?, yetki = ?, adsoyad = ?, telno = ?  WHERE id = ?";
                var sa = conn.prepareStatement(sql);
                sa.setString(1, uNick);
                sa.setString(2, password);
                sa.setString(3, autho);
                sa.setString(4, uName);
                sa.setString(5, contact);
                sa.setString(6, selectedID);
                int sonuc = sa.executeUpdate();
                
                if (sonuc > 0 ){
                    JOptionPane.showMessageDialog(this, "Kullanıcı başarıyla güncellendi!");
                    KullaniciVerileriniGoster veriCekici = new KullaniciVerileriniGoster();
                    veriCekici.verileriGetir(ktablo);
                    
                }else {
                    JOptionPane.showMessageDialog(this, "Güncelleme işlemi başarısız!");
                    
                }
                conn.close();
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hata: " +e.getMessage());
            }
        }
        
    }else{
        JOptionPane.showMessageDialog(this, "Lütfen güncellemek için bir kullanıcı seçin.");
    }  // TODO add your handling code here:
    }//GEN-LAST:event_upBTNActionPerformed
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConTXT;
    private javax.swing.JTextField NickTXT;
    private javax.swing.JButton addBTN;
    private javax.swing.JComboBox<String> authoCombo;
    private javax.swing.JButton backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable ktablo;
    private javax.swing.JPasswordField passTXT;
    private javax.swing.JTextField uNameTXT;
    private javax.swing.JButton upBTN;
    // End of variables declaration//GEN-END:variables
}
